export const Data = [
    {
        value:0,
        price: 0,
        upPrice:0,
        upPercent: 90,
        downPercent: 0,
        desPercent: 0,
        url:"/img/weapon/0.png",
    },
    {
        value:1,
        price: 50,
        upPrice:0,
        upPercent: 85,
        downPercent: 0,
        desPercent: 0,
        url:"/img/weapon/1.png",
    },
    {
        value:2,
        price: 100,
        upPrice:0,
        upPercent: 80,
        downPercent: 0,
        desPercent: 0,
        url:"/img/weapon/2.png",
    },
    {
        value:3,
        price: 200,
        upPrice:0,
        upPercent: 75,
        downPercent: 0,
        desPercent: 0,
        url:"/img/weapon/3.png",
    },
    {
        value:4,
        price: 300,
        upPrice:0,
        upPercent: 70,
        downPercent: 0,
        desPercent: 0,
        url:"/img/weapon/4.png",
    },
    {
        value:5,
        price: 500,
        upPrice:0,
        upPercent: 70,
        downPercent: 0,
        desPercent: 0,
        url:"/img/weapon/5.png",
    },
    {
        value:6,
        price: 700,
        upPrice:500,
        upPercent: 65,
        downPercent: 0,
        desPercent: 0,
        url:"/img/weapon/6.png",
    },
    {
        value:7,
        price: 1200,
        upPrice:700,
        upPercent: 60,
        downPercent: 0,
        desPercent: 0,
        url:"/img/weapon/7.png",
    },
    {
        value:8,
        price: 1500,
        upPrice:900,
        upPercent: 55,
        downPercent: 0,
        desPercent: 0,
        url:"/img/weapon/8.png",
    },
    {
        value:9,
        price: 2000,
        upPrice:1000,
        upPercent: 50,
        downPercent: 0,
        desPercent: 0,
        url:"/img/weapon/9.png",
    },
    {
        value:10,
        price: 55000,
        upPrice:2500,
        upPercent: 47,
        downPercent: 0,
        desPercent: 0,
        url:"/img/weapon/10.png",
    },
    {
        value:11,
        price: 120000,
        upPrice:5000,
        upPercent: 43,
        downPercent: 3,
        desPercent: 0,
        url:"/img/weapon/11.png",
    },
    {
        value:12,
        price: 150000,
        upPrice:10000,
        upPercent: 40,
        downPercent: 5,
        desPercent: 0,
        url:"/img/weapon/12.png",
    },
    {
        value:13,
        price: 250000,
        upPrice:20000,
        upPercent: 37,
        downPercent: 7,
        desPercent: 0,
        url:"/img/weapon/13.png",
    },
    {
        value:14,
        price: 650000,
        upPrice:50000,
        upPercent: 32,
        downPercent: 10,
        desPercent: 0,
        url:"/img/weapon/14.png",
    },
    {
        value:15,
        price: 1200000,
        upPrice:70000,
        upPercent: 26,
        downPercent: 15,
        desPercent: 0,
        url:"/img/weapon/15.png",
    },
    {
        value:16,
        price: 1800000,
        upPrice:100000,
        upPercent: 22,
        downPercent: 20,
        desPercent: 20,
        url:"/img/weapon/16.png",
    },
    {
        value:17,
        price: 2500000,
        upPrice:150000,
        upPercent: 17,
        downPercent: 25,
        desPercent: 27,
        url:"/img/weapon/17.png",
    },
    {
        value:18,
        price: 4000000,
        upPrice:200000,
        upPercent: 15,
        downPercent: 30,
        desPercent: 35,
        url:"/img/weapon/18.png",
    },
    {
        value:19,
        price: 6500000,
        upPrice:350000,
        upPercent: 13,
        downPercent: 40,
        desPercent: 50,
        url:"/img/weapon/19.png",
    },
    {
        value:20,
        price: 20000000,
        upPrice:0,
        upPercent: 0,
        downPercent: 0,
        desPercent: 0,
        url:"/img/weapon/20.png",
    },
]